package promptcompat

import (
	"encoding/json"
	"log"
	"strings"

	"github.com/zhangguoguo1314/mimo-free-api/internal/adapter"
)

// ExtractFirstUserMessage extracts the first user message text from Anthropic messages.
// Used to derive a stable conversationId for MiMo conversation reuse.
func ExtractFirstUserMessage(msgs []adapter.AnthropicMessage) string {
	for _, msg := range msgs {
		if msg.Role == "user" {
			return extractTextFromContent(msg.Content)
		}
	}
	return ""
}

// ExtractLatestUserMessage extracts the latest user message text from Anthropic messages.
// This becomes the query sent to MiMo (instead of the full conversation history).
// Handles both string and array content formats, including tool_result blocks.
// Skips auto-generated messages like "predict next message" from MiMo Code.
func ExtractLatestUserMessage(msgs []adapter.AnthropicMessage) string {
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == "user" {
			text := extractTextFromContent(msgs[i].Content)
			if isAutoGeneratedMessage(text) {
				log.Printf("[filter] skipping auto-generated Anthropic message (len=%d): %q", len(text), truncate(text, 100))
				continue
			}
			return text
		}
	}
	return ""
}

// extractTextFromContent extracts text from Anthropic message content.
// Content can be a string or an array of content blocks.
func extractTextFromContent(content interface{}) string {
	switch c := content.(type) {
	case string:
		return c
	case []interface{}:
		var parts []string
		for _, block := range c {
			b, ok := block.(map[string]interface{})
			if !ok {
				continue
			}
			blockType, _ := b["type"].(string)
			switch blockType {
			case "text":
				if text, ok := b["text"].(string); ok {
					parts = append(parts, text)
				}
			case "tool_result":
				// Extract text from tool_result content
				if rc, ok := b["content"]; ok {
					parts = append(parts, extractTextFromContent(rc))
				}
			case "tool_use":
				// Skip tool_use blocks (assistant's tool calls)
				continue
			}
		}
		return strings.Join(parts, "\n")
	default:
		// Try JSON marshal/unmarshal for unexpected types
		b, err := json.Marshal(content)
		if err != nil {
			return ""
		}
		var s string
		if json.Unmarshal(b, &s) == nil {
			return s
		}
		return ""
	}
}

// isAutoGeneratedMessage detects auto-generated messages from MiMo Code features
// like "predict next message" that should not be forwarded to MiMo.
func isAutoGeneratedMessage(s string) bool {
	lower := strings.ToLower(s)
	autoPatterns := []string{
		"based on the conversation above",
		"write the user's most likely next message",
		"most likely next message",
		"user's most likely",
		"above conversation",
	}
	for _, p := range autoPatterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	// Chinese patterns
	zhPatterns := []string{
		"根据以上对话",
		"根据对话上下文",
		"最可能发送的下一条消息",
		"预测用户的下一条消息",
		"写出用户最可能",
		"用户最可能的下一条",
		"用户最可能发送",
	}
	for _, p := range zhPatterns {
		if strings.Contains(s, p) {
			return true
		}
	}
	return false
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
